### ISSUE TITLE
Localization changes are bound to OS language

### ISSUE THREAD

**Issue by mrahimygk** [YarikSOffice/lingver#19]
In some recently-released phones, users cannot change the language inside the app which is using lingver, the language is not independent of the OS language.

This happens in samsung A10, api 29 and xiaomi redmi k20 pro api 29 
But It works fine in Samsung j7Pro api 28

Maybe it's an issue in api level?

**Comment by YarikSOffice** [comment]
Hi @m-rahimy

Have you managed to reproduce it using the sample project?

**Comment by m-rahimy** [comment]
I believe It happens when we add the new androidx prefsManager dependency in our project (what a weird issue). This seems not related to the lingver library.

**Comment by YarikSOffice** [comment]
Hmm, adding of androidx prefs manager doesn't break the library, according to my tests.
Any further details are appreciated @m-rahimy

**Comment by NikiFoD** [comment]
Could it be an issue with the App Bundles? If your phone doesn't have the language in your settings, it is not downloaded using app bundle, unless you explicitly say so.
So, language change will work on debug mode, but not in release.
Check out this [post](https://stackoverflow.com/questions/52731670/android-app-bundle-with-in-app-locale-change)

**Comment by YarikSOffice** [comment]
@NikiFoD great remark! I'll consider adding this info to the description.

**Comment by AlaaZarifa** [comment]
> Could it be an issue with the App Bundles? If your phone doesn't have the language in your settings, it is not downloaded using app bundle, unless you explicitly say so.
> So, language change will work on debug mode, but not in release.
> Check out this [post](https://stackoverflow.com/questions/52731670/android-app-bundle-with-in-app-locale-change)

It's true, Google introduced a new App Bundle format to split apk files in smaller sizes when they’re being installed on the client devices. However, this means that we cannot have dynamic language changes in our applications.
To prevent that split for language files we need to add extra lines in our `build.gradle` file inside the app folder like below.

```
android {
    //...
    bundle {
        language {
            enableSplit = false
        }
    }
}
```

**Comment by YarikSOffice** [comment]
Finally, looks like the issue is not related to the library. Feel free to reopen if necessary.
