### ISSUE TITLE
Update already fetched locale-based data in activities and fragments that reside in the backstack after changing locale.

### ISSUE THREAD

**Issue by Maxrang** [YarikSOffice/lingver#21]
This is not an issue with lingver but more like the followup that I've never figured out.
In light of
> Note that you need to update all already fetched locale-based data manually. Lingver is not responsible for that.

I understand that Lingver's responsibility ends after updating the locale using 
`Lingver.getInstance().setLocale(this, language)`

what I have is a button in a custom ActionBar, pressing that button calls the `Lingver.getInstance().setLocale(this, language)` and the ActionBar is used on every activity on the project, so that on any activity the user is able to change the language at any time by pressing that button.

the main issue is when there are activities and/or fragments that are already open in the backstack.

so what's the go-to approach? how can one change the data (e.g. TextView, RecyclerView, etc...) that are already fetched in activities and fragments that are on the backstack?

I've tried to override `onConfigurationChanged` inside my activity class and reset my views there 
but it was never called even after adding` android:configChanges="locale|layoutDirection"` to the activity in the android manifest

I have also tried to call `recreate()` after using `Lingver.getInstance().setLocale(this, language)`
it does work as it resets the activity but it gave me literal hell for my viewpager and fragments configuration so I'm looking for potentially better alternatives.

**Comment by YarikSOffice** [comment]
Hi @Maxrang,

There is no silver bullet for refreshing the backstack. That's exactly the reason why Lingver doesn't do that for you.

In your case, I'd suggest keeping following the `recreate()` approach (btw you have to call it for each activity) making sure your activities/fragments correctly restore their state. I don't see any better alternative, unfortunately. 

>I've tried to override onConfigurationChanged inside my activity class and reset my views there
You can always implement a similar callback manually, but I'd not recommend this approach since it requires lifetime maintenance.

**Comment by jemshit** [comment]
Every Activity should have which locale is used when they are created. In `onResume()`, you should check "localeWhenCreated==currentSelectedLocale", if not, recreate(). So, when you return back to Activity in stack, it will recreate itself. Beware, Fragments in Activity will still be there in FragmentManager [after recreate.](https://stackoverflow.com/questions/26849905/fragments-not-destroyed-when-recreate-activity/46558908#46558908)
