### ISSUE TITLE
Does not work for app_names and icons in Notification 

### ISSUE THREAD

**Issue by angelkoh** [YarikSOffice/lingver#3]
can you update the library, such that the App name in Notification gets updated when a locale is changed?

[https://i.stack.imgur.com/qZKbq.png](url)

**Comment by YarikSOffice** [comment]
Hi @angelkoh 
May I know a bit more information about your specific use case:
1. What `Context` do you use to display the string/notification?
2. Do you send a notification before setting a new locale?

Note that if a notification is sent before you set a new locale, then you have to update the notification manually. Lingver can't do that for you.

**Comment by YarikSOffice** [comment]
Closed due to inactivity. Please, feel free to reopen if needed.

**Comment by shikha1992** [comment]
@YarikSOffice  I am also facing the same issue in release build. I have `bundle {
        language {
            enableSplit = false
        }
    }` in place. 
Language translation is working fine for app but not for notification in release version. 
I have below method when notification receive 
 `Lingver.getInstance().setLocale(this, Lingver.getInstance().getLanguage());`

In proguard I have set rule 
` -keep class com.yariksoffice.lingver.** { *; }`

**Comment by YarikSOffice** [comment]
@shikha1992 Would you mind providing more context regarding your issue by answering the same question above?

a few more things to know:

1. Is it a system notification or a custom one?
2. How do u trigger them?

I'd appreciate a small sample app to reproduce it instead of answering the above. Thanks
