### ISSUE TITLE
Works on local, but not in Google Play

### ISSUE THREAD

**Issue by peporroncin** [YarikSOffice/lingver#30]
Hi,
I've testing the library to change language programatically and it works perfectly. The problem is when I put the app on Google Play. The same app doesn't work, doesn't change the language. 

I've tried 2 times, it's exactly the same app on local and Google Play. 

Anyone with same issue?

Thanks a lot!

**Comment by YarikSOffice** [comment]
Hi @peporroncin,

Your issue might be related to [App Bundles](https://developer.android.com/guide/app-bundle).
Please refer to the similar issue #27 for a solution.

**Comment by peporroncin** [comment]
Sorry @YarikSOffice, I hadn't seen the related issue.

I'm going to test the solution. 

Thanks in advance.

**Comment by peporroncin** [comment]
After applying this #27 solution, everything works properly, even with the Google Play app. 

`android {
    bundle {
        language {
            enableSplit = false
        }
    }
}`

Thank you very much for this fantastic library.
