### ISSUE TITLE
Stops working in production app

### ISSUE THREAD

**Issue by svrlopatrik** [YarikSOffice/lingver#32]
The library works fine when I install it directly from Android Studio.

However, when I create signed app bundle, upload it to play store and download it from there it stops working. Language is always in system's locale. I'm not using proguard which should change the source code.
I own devices with API 29, 23, 21 and only 21 works correctly on play store's version.
Any idea how to fix this strange behavior?

**Comment by YarikSOffice** [comment]
Hi @svrlopatrik,

Looks like your issue is related to App Bundles.
Please refer to the similar issue #27 for a solution.
