### ISSUE TITLE
Khmer Language Not Working

### ISSUE THREAD

**Issue by BhargavSavasani** [YarikSOffice/lingver#33]
This Library in Khmer (Cambodia) Language not Working

**Comment by YarikSOffice** [comment]
Hi @BhargavSavasani ,

I've checked Khmer (Cambodia) Language and it works as expected for me. 

Values folder: `values-km-rKH`
Locale: `km_KH`  


Could you please elaborate on how you use the library and what goes wrong in your case? Code snippets are highly appreciated.

**Comment by BhargavSavasani** [comment]
Hi @YarikSOffice 

Please Give Any Link And Project you Work on the Khmer Language 
Because Currently, my Side Not Working

**Comment by YarikSOffice** [comment]
@BhargavSavasani Here is a test branch for the sample app containing Khmer language:
https://github.com/YarikSOffice/lingver/compare/example_khmer_language

**Comment by BhargavSavasani** [comment]
Hi @YarikSOffice 

Please update in Sample 
Because Currently still not Working 
if you Update in the sample then Download and check this

**Comment by YarikSOffice** [comment]
@BhargavSavasani Please give me more details with code snippets/screenshots, so I can help with your issue.

**Comment by BhargavSavasani** [comment]
@YarikSOffice 

Add strings.xml file in values-km-rKH
now Setting in Change Language 

![image](https://user-images.githubusercontent.com/42731066/86119188-a831af80-baef-11ea-9841-22c4298cae12.png)
![image](https://user-images.githubusercontent.com/42731066/86119224-b5e73500-baef-11ea-96e8-801f7b2643a3.png)
![image](https://user-images.githubusercontent.com/42731066/86119253-c0a1ca00-baef-11ea-9e32-4426a68ab6db.png)
![image](https://user-images.githubusercontent.com/42731066/86119270-c8fa0500-baef-11ea-8877-b37f9593fbbe.png)

**Comment by YarikSOffice** [comment]
Well, I don't see any issues so far. Let me figure out a few more things:

1. Do you call `setLocale` somewhere outside this class? I'm curious why do you use additional pref setting for language since you can always get the current language via `lingver.getLanguage()`.
2. Do you use [App Bundles](https://developer.android.com/guide/app-bundle)?
3. How do you restart your app inside `restartApp()` method?

**Comment by BhargavSavasani** [comment]
no i am not use app bundles
restart app is a function to restart app

![image](https://user-images.githubusercontent.com/42731066/86121154-25aaef00-baf3-11ea-9fca-ff2eb8595298.png)

**Comment by YarikSOffice** [comment]
@BhargavSavasani Do you use a single activity with fragments in your app? or activity per screen? 

since if you are using multiple activities you have to restart all of them, but looks like your code restarts the top one only.

**Comment by BhargavSavasani** [comment]
@YarikSOffice 

But When u Call activity.finishAffinity means Restart the Full App

**Comment by BhargavSavasani** [comment]
@YarikSOffice 

please If u work khmer lang. in your project and its working 
then send me full project so i am check this

**Comment by YarikSOffice** [comment]
the full sample project using khmer is here: 
https://github.com/YarikSOffice/lingver/compare/example_khmer_language

Have you checked it out?

**Comment by BhargavSavasani** [comment]
@YarikSOffice 

but This Code not Update in Your Sample Project
If u update this Code in Sample Project then

**Comment by YarikSOffice** [comment]
This is a separate branch specifically for khmer language. Please check out this branch and clone/download the repository.

**Comment by BhargavSavasani** [comment]
@YarikSOffice 
ok I Got it 
Thanks
