### ISSUE TITLE
Why "followSystemLocale" is not true by default?

### ISSUE THREAD

**Issue by smokxx** [YarikSOffice/lingver#36]
I was quite surprised when I realized that `isFollowingSystemLocale` is false by default. Let me explain my use case, maybe I'm missing something. I want my app locale to match system locale, unless the user specified otherwise explicitly in the app settings. So if the user just launches the app, then changes the system locale, I want the app to automatically change the locale to the system one. If the user then changes the app locale to a different one in settings, I want that locale to stick, so now system locale doesn't matter anymore.
If isFollowingSystemLocale was 'true' by default, everything would work naturally. I would use Lingver.setLocale() only when the user changes the locale in app settings. But since isFollowingSystemLocale is false by default, the first call to Lingver.init() on the first app run persists the locale, and subsequent system locale changes don't have any effect. So to achieve what I want, I need to call `setFollowSystemLocale(true)`, but only on the first app run. Which is doable, but a bit annoying.

At the same time I realize that you probably can't change the default value now, because all apps with Lingver that didn't change followSystemLocale explicitly would start behaving differently.

And thank you for creating the library and publishing that blog post!

**Comment by YarikSOffice** [comment]
Hi, @smokxx

I totally understand your concern and agree that your expectations are natural.
However, `isFollowingSystemLocale` API was introduced recently and we didn't change this behavior to keep backward compatibility.

I plan to set `setFollowSystemLocale` to true by default along with the next breaking changes. No ETA, unfortunately. 
Until then you have to use the mentioned workaround to achieve this behavior.


Thanks for the great feedback and your interest in the library.
This question will definitely come in handy for other users that face a similar issue.

**Comment by kenneth-leong-gt** [comment]
just a suggestion, I think its possible to check the preference store for the absence of all of the below preference keys as in indication that Lingver has been initialised on a freshly installed app.

```
        private const val LANGUAGE_KEY = "language_key"
        private const val FOLLOW_SYSTEM_LOCALE_KEY = "follow_system_locale_key"
        private const val LANGUAGE_JSON_KEY = "language"
        private const val COUNTRY_JSON_KEY = "country"
        private const val VARIANT_JSON_KEY = "variant"
```
 This is what i am thinking of doing.
 
 ```
 private fun initMultiLanguage() {
        val localeStore = PreferenceLocaleStore(this)
        Lingver.init(application = this, store = localeStore).run {
            with(getSharedPreferences("lingver_preference", Context.MODE_PRIVATE)) {
                // check if Linver is init on a fresh install 
                if (
                    !contains("follow_system_locale_key") &&
                    !contains("country") &&
                    !contains("language") &&
                    !contains("variant")
                ) {
                    setFollowSystemLocale(this@App)
                }
            }
        }
    }
    ```
    
Maybe to both preserve backward compatibility, Lingver can provide a function/method to check if the `store` is a fresh store by doing something like the above and lets dev decide if they wan to manually set the `setFollowSystemLocale(true)`?

**Comment by kenshin171** [comment]
just a suggestion, I think its possible to check the preference store for the absence of all of the below preference keys as in indication that Lingver has been initialised on a freshly installed app.

```
        private const val LANGUAGE_KEY = "language_key"
        private const val FOLLOW_SYSTEM_LOCALE_KEY = "follow_system_locale_key"
        private const val LANGUAGE_JSON_KEY = "language"
        private const val COUNTRY_JSON_KEY = "country"
        private const val VARIANT_JSON_KEY = "variant"
```
 This is what i am thinking of doing.
 
 ```
 private fun initMultiLanguage() {
        val localeStore = PreferenceLocaleStore(this)
        Lingver.init(application = this, store = localeStore).run {
            with(getSharedPreferences("lingver_preference", Context.MODE_PRIVATE)) {
                // check if Linver is init on a fresh install 
                if (
                    !contains("follow_system_locale_key") &&
                    !contains("country") &&
                    !contains("language") &&
                    !contains("variant")
                ) {
                    setFollowSystemLocale(this@App)
                }
            }
        }
    }
    ```
    
Maybe to both preserve backward compatibility, Lingver can provide a function/method to check if the `store` is a fresh store by doing something like the above and lets dev decide if they wan to manually set the `setFollowSystemLocale(true)`?
