### ISSUE TITLE
Does not work good with AAB instead of APK

### ISSUE THREAD

**Issue by arnowelzel** [YarikSOffice/lingver#37]
I just discovered on a device by Xiaomi with MIUI12 that translations may be missing if you publish the app on Google Play as AAB (Android App Bundle). After changing to the traditional APK everything was OK. I believe, when using AAB Google Play only installs the language which is used by the device - as the idea of AAB is to save storage space.

Maybe this should be mentioned in the documentation.

**Comment by YarikSOffice** [comment]
Hey @arnowelzel,

You are right, it won't work with App Bundle out of the box.

However, it's already mentioned in the README. Please, refer to [the following section](https://github.com/YarikSOffice/lingver#app-bundles).

**Comment by arnowelzel** [comment]
Ok, thanks for pointing this out - just didn't RTFM ;-)
