### ISSUE TITLE
Build error when adding lingver dependency

### ISSUE THREAD

**Issue by aliakbarmostafaei** [YarikSOffice/lingver#4]
I get this build error when I add the dependency: 
`More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'`

I'm using Android Studio 3.5.2 with Kotlin 1.3.50.

**Comment by YarikSOffice** [comment]
Hi @aliakbarmostafaei 
In meanwhile, you can try excluding it as described here:
https://stackoverflow.com/questions/44509608/duplicate-files-copied-in-apk-meta-inf-library-release-kotlin-module

I'll try to fix it inside the library.

**Comment by YarikSOffice** [comment]
Fixed in v1.2.2.
