### ISSUE TITLE
Could not find com.github.YarikSOffice:lingver:1.3.0

### ISSUE THREAD

**Issue by Sharabaddin** [YarikSOffice/lingver#40]
**i add**
`maven { url 'https://jitpack.io' }`

`implementation "com.github.YarikSOffice:lingver:1.3.0"`

**but**

```
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.YarikSOffice:lingver:1.3.0.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by YarikSOffice** [comment]
@Sharabaddin It looks like you did not declare the repository properly.

Make sure to declare

```maven { url 'https://jitpack.io' }```

within the `allprojects` clausure.

**Comment by YarikSOffice** [comment]
Closed due to inactivity. Assuming that the issue has been resolved.
