### ISSUE TITLE
How to get default system locale?

### ISSUE THREAD

**Issue by c0dehunter** [YarikSOffice/lingver#41]
I don't know if this is a problem with me using this library in Java project, or am I missing something? I just want to get default system locale (the phone's locale).

---

    Lingver.getInstance().systemLocale.getLanguage();

> error: systemLocale has private access in Lingver

---

I also tried:

    Lingver.defaultLocale.getLanguage();

> error: defaultLocale has private access in Lingver

---

Then there is `getSystemLocale$com_yariksoffice_lingver_library()`:

![image](https://user-images.githubusercontent.com/1484658/112562460-9a3b6180-8dd7-11eb-98ea-06552835c9b8.png)

> Usage of Kotlin internal declaration from different module

**Comment by YarikSOffice** [comment]
Usually, you don't need to deal with the system locale while using Lingver.

There 2 commonly used scenarios for this library:
1. Enforce a specific locale via `setLocale()` and access this locale anytime via `lingver.getLocale()`.
2. Configure Lingver to follow the system locale via `setFollowSystemLocale()`. In this case, `getLocale()` will always return the system locale.

If you want to get the real system locale which is not yet overriden by Lingver, you can always use `Locale.getDefault()` before `Lingver.init()` call.

**Comment by c0dehunter** [comment]
Thank you. I did as you mentioned in the last part: saved default system locale by calling `Locale.getDefault()` just before `Lingver.init()` and it works well.
