### ISSUE TITLE
target 30 not working

### ISSUE THREAD

**Issue by Cangol** [YarikSOffice/lingver#42]
target 30 not working

**Comment by YarikSOffice** [comment]
@Cangol could you elaborate on what is not working for you when targeting sdk 30?
The sample project works as usual.

**Comment by naufalprakoso** [comment]
Same with me. This library doesn't work on Android SDK 30

**Comment by naufalprakoso** [comment]
Are you using AAB? @Cangol 
If yes, you should try to add this thing on build.gradle
```
bundle {
        language {
            enableSplit = false
        }
    }
```

**Comment by YarikSOffice** [comment]
According to my testing, the library works as usual while targeting sdk 30.

@Cangol Could you elaborate on your issue in more details? Thanks

**Comment by YarikSOffice** [comment]
Closed due to inactivity.
