### ISSUE TITLE
How to check instance is initialized or not

### ISSUE THREAD

**Issue by honeysamresh** [YarikSOffice/lingver#45]
How to check instance is initialized or not
like Lingver.getInstance().isInitialized

**Comment by YarikSOffice** [comment]
Currently, there is no way to do that as the library is designed to be initialized only once during the app launch.

Could you please elaborate on why you need this api?

**Comment by honeysamresh** [comment]
according to your api i initialized it once in main activity. when i am changing the language i am restarting the whole app. This time the app is crashing showing "Instance already initialized" in logcat. so it ll be better if we can check wheather the instance is initialized or not . if initialized simply start the app otherwise create the instance in mainActivity

you can add a function like below

```
if(Lingver.getinstance() = null){
//initialize the instance}
else {
//start the app
}

```

**Comment by YarikSOffice** [comment]
@honeysamresh Could you try to initialize Lingver in `Application.onCreate`? that would prevent the crash on configuration change

See [an example here](https://github.com/YarikSOffice/lingver/blob/master/sample/src/main/java/com/yariksoffice/lingver/App.kt#L38)

**Comment by honeysamresh** [comment]
here is my java code ```

    protected void onCreate(Bundle savedInstanceState) {
        mainPreference = PreferenceManager.getDefaultSharedPreferences(this);
        editor = mainPreference.edit();
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        activityFlag = getIntent().getIntExtra("flags",0);

            if (activityFlag != 1){
                try {
                    Lingver.init(getApplication(),"en");
                } catch (Exception e){
                    Log.d(TAG, "onCreate: " + e.toString());
                }
                Log.d(TAG, "onCreate: Instance Created");
                } else {
                    Log.d(TAG, "Instance already there");
                }
```  i am initializing in onCreate only

**Comment by YarikSOffice** [comment]
@honeysamresh could you move this code to the `Application.onCreate` method and let me know whether it solves your issue. Thanks

**Comment by YarikSOffice** [comment]
Closed due to inactivity
