### ISSUE TITLE
MobileAds.initialize changes locale to default

### ISSUE THREAD

**Issue by famfamfam** [YarikSOffice/lingver#47]
Calling MobileAds.initialize in onViewCreated change resources configuration locale to default
So, I think problem is in using deprecated updateConfiguration in Lingver...

**Comment by YarikSOffice** [comment]
@famfamfam yep, it might be the case. 
If other libraries change the device locale, it will affect the operation of Lingver. I don't see any ways to prevent that, unfortunately. 

Please consider setting the locale back after MobileAds is initialized.
