### ISSUE TITLE
Note that you need to update all already fetched locale-based data manually.

### ISSUE THREAD

**Issue by binaryKarmic** [YarikSOffice/lingver#5]
I am seeing some unexpected behavior even after calling
`Lingver.getInstance().setLocale(this, language)`
properly. The new language locale strings won`t show up unless app is exited and started again.
I guess it is related to the point mention in notes "Note that you need to update all already fetched locale-based data manually. Lingver is not responsible for that."
What exactly means by updating already fetched data manually and how to do it? What will be the best-practice for this ?

**Comment by YarikSOffice** [comment]
Hi @binaryKarmic 

may I know a bit more about your use case:

1. what exactly is not translated?
2. do you load this data before or after you call `setLocale`?

>What exactly means by updating already fetched data manually and how to do it? What will be the best-practice for this ?

It means that you basically need to restart a whole activity back stack to apply a new locale.

**Comment by YarikSOffice** [comment]
Closed due to inactivity. Please, feel free to reopen if needed.
