### ISSUE TITLE
AAB release build not working for notification translation

### ISSUE THREAD

**Issue by shikha1992** [YarikSOffice/lingver#50]
When app in release mode, aab file do not support arabic translation. 
In app gradle I already have - 
`bundle {
        language {
            enableSplit = false
        }
    }`
In proguard file, I have 
`-keep class com.yariksoffice.lingver.** { *; }`

I am calling below method on Message Recieved(Push notification is received)
`Lingver.getInstance().setLocale(this, Lingver.getInstance().getLanguage());`

please suggest @YarikSOffice

**Comment by YarikSOffice** [comment]
Thanks for submitting this issue!

Would you mind providing more context regarding your issue

1. Is it a system notification or a custom one?
2. How do you trigger them? What Context do you use?
3. Have you tried setting the locale in your service/receiver before sending a notification?

I'd appreciate a small sample app to reproduce it as an alternative to answering the above. 
Thanks

**Comment by shikha1992** [comment]
I got it fixed. Tried setting locale in service class and it works. 
This is system notification.
