### ISSUE TITLE
System-Default Language-Key?

### ISSUE THREAD

**Issue by g88704** [YarikSOffice/lingver#9]
Hi,

first of all thanks for your Lingver library project.

Is there a way or a "special language-key" that always returns the

  defaultLocale: Locale = Locale.getDefault()

from the app-start?

Thanks and Regards

**Comment by YarikSOffice** [comment]
Hi @g88704 
I don't think I get your question. 

>Is there a way or a "special language-key" that always returns the defaultLocale: Locale = Locale.getDefault()
What do you mean by `returns` in this context? 
Could you please describe in a bit more details what you want to achieve.

**Comment by g88704** [comment]
Yes I will try to explain:

In my Language selection I want to have the following entries:
- System language
- English
- German
- ...

The entry System language should always use the language that is set as your default language in the Android System settings. 

So if you change the default Android system language and you restart your linger-app it should use the new system default language key. 

Right now you use the System default language only for the first time, if no linger prefs are stored at all. 

Thanks and Regards

**Comment by YarikSOffice** [comment]
okay, I got it.

Unfortunately, Lingver doesn't support that at the moment. I'll consider it as a feature request since it might be really useful.

**Comment by g88704** [comment]
I wrote a simple wrapper around your Lingver-library that implement the "System language" feature. My quick solution works like this:

1) I store a separate Lang-Key in my own prefs. The value "_" is used for the System-Language entry
2) During the App start I store the Locale.getDefault in a member called mStartupLocale
3) My wrapper method to set the Linger language looks like this:
    fun setLingerLanguage(pLang: String?) {
        if (pLang.isNullOrBlank() || pLang == "_") {
            Lingver.getInstance().setLocale(mCtx, mStartupLocale)
        } else {
            Lingver.getInstance().setLocale(mCtx, pLang)
        }
    }
4) And here the Lingver-Init method during the app-start:
        val lLingverStore = PreferenceLocaleStore(this)
        val lLingver = Lingver.init(this, lLingverStore)

        val lPrefLang = getMyOwnPrefLanguage()
        setLingerLanguage(lPrefLang)

It seems to work, so thanks again for your library...

Kind Regards

**Comment by ranco980** [comment]
That is a very important feature! Any plan to implement?

**Comment by YarikSOffice** [comment]
@ranco980 we are currently working on that
